### ISSUE TITLE
Create Badges

### ISSUE THREAD

**Issue by seanmerron** [RevolutionVA/HRDevFest-Planning#18]
Include swag sponsor logo on badges.
Different color lanyard for staff.
To be assigned to Alex...

**Comment by aproaps** [comment]
1. Get estimate 
2. Design badges
3. Order lanyards
3 weeks in advance, the rest can be blank:
4. Name list spreadsheet 
5. Order badges

**Comment by erikpmp** [comment]
@aproaps Done, right?
