### ISSUE TITLE
Setup Geek Out Room

### ISSUE THREAD

**Issue by seanmerron** [RevolutionVA/HRDevFest-Planning#19]
Possible usability lab. Node bots, VR, board games. Something Googly. This would be the room where the TV was at last year that wasn't used. Small but can having something going on there all day. Can even add 3rd tab to schedule if we split the room use up during the day. Ask Brandon/MakersSpace for help? Add to website

**Comment by seanmerron** [comment]
Possible usability lab

**Comment by seanmerron** [comment]
Node bots, VR, board games

**Comment by seanmerron** [comment]
Add to website

**Comment by seanmerron** [comment]
Something Googly

**Comment by erikpmp** [comment]
we doing this?

**Comment by 1kevgriff** [comment]
We *could* in that back room?
