### ISSUE TITLE
Create Signage

### ISSUE THREAD

**Issue by seanmerron** [RevolutionVA/HRDevFest-Planning#8]
To be assigned to Alex...

**Comment by aproaps** [comment]
To do (just to keep myself organized) :
1. List of signs needed
2. Design poster 
3. Design schedule
4. Design signs
5. Print posters
6. Print schedule
7. Print signs

**Comment by erikpmp** [comment]
Done?

**Comment by aproaps** [comment]
No, still need to print signage for the rooms (we decided just doing basic designs on regular paper for those).
